###############################################################################
# Copyright (c) 2022, 2026 SWTChart project
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# https://www.eclipse.org/legal/epl-2.0/.
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#     Matthias Mailänder - initial API and implementation
###############################################################################

name: Continuous Integration
on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout SWTChart
      uses: actions/checkout@v6

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.12

    - name: Build with Maven on X Window Virtual Framebuffer
      run: xvfb-run --auto-servernum mvn -Pjavadoc --T 1C verify --B -ntp -Dstyle.color=always
